name: Deploy Medusa to AWS ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com

    - name: Build & Push Docker image
      run: |
        docker build -t medusa-backend .
        docker tag medusa-backend:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest
        docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest

    - name: Run Terraform
      run: |
        terraform init
        terraform apply -auto-approve
